/**!
	Fold
	(Un)folds content when a trigger/cmd is activated. Not an accordion, each fold is independent. Seen on mobile catalogue / Exhibitor details

	@contributors: Philippe Vayssière (Alsacréations)
	@date-created: 2015-11-02
	@last-update: 2015-11-03
 */

;(function($) {

	var selFoldContainer = '.js-fold',
		selFoldCmd = '.js-fold-cmd',
		selFoldTarget = '.js-fold-target',
		$foldContainer = $(selFoldContainer),
		$foldCmd = $(selFoldCmd),
		$selFoldTarget = $(selFoldTarget);

	// Init: hides every foldable content
	$(document).ready(function() {
		$selFoldTarget.addClass('js-hidden'); // Content initially hidden. This class should already be in HTML code generated by server, this is just in case©
	});

	// Hide/show content after click on command button
	$foldContainer.on('click', selFoldCmd, function() {
		$(this).toggleClass('is-active');
		$(this).closest(selFoldContainer).find(selFoldTarget).toggleClass('js-hidden');
	});

})(jQuery);